[[items]]
title = "8 1/2"

[[items]]
title = "12 Monkeys"

[[items]]
title = "A Scanner Darkly"

[[items]]
title = "A Silent Voice"

[[items]]
title = "A Time to Kill"

[[items]]
title = "Akira"

[[items]]
title = "Basic Instinct"

[[items]]
title = "Birdman or (The Unexpected Virtue of Ignorance)"

[[items]]
title = "Blood Red Sky"

[[items]]
title = "Casablanca"

[[items]]
title = "Cinema Paradiso (Theatrical Cut)"

[[items]]
title = "Coco"

[[items]]
title = "Coherence"

[[items]]
title = "Crazy Rich Asians"

[[items]]
title = "Don't Worry Darling"

[[items]]
title = "Enter the Void"

[[items]]
title = "Extraction"

[[items]]
title = "Frailty"

[[items]]
title = "Ghost in the Shell"

[[items]]
title = "Going in Style"

[[items]]
title = "Hugo"

[[items]]
title = "I Lost My Body"

[[items]]
title = "Isle of Dogs"

[[items]]
title = "It's What's Inside"

[[items]]
title = "Jin-Roh: The Wolf Brigade"

[[items]]
title = "Kubo and the Two Strings"

[[items]]
title = "Laputa: Castle in the Sky"

[[items]]
title = "Le Dîner de Cons"

[[items]]
title = "Let the Right One In"

[[items]]
title = "Loving Vincent"

[[items]]
title = "Mirage"

[[items]]
title = "Moonrise Kingdom"

[[items]]
title = "Multiplicity"

[[items]]
title = "Nausicaa of the Valley of the Wind"

[[items]]
title = "Never Let Me Go"

[[items]]
title = "Okja"

[[items]]
title = "One Flew Over the Cuckoo's Nest"

[[items]]
title = "Only Lovers Left Alive"

[[items]]
title = "Other People"

[[items]]
title = "Pane e Tulipani"

[[items]]
title = "Paprika"

[[items]]
title = "Patema Inverted"

[[items]]
title = "Perfect Blue"

[[items]]
title = "Poison"

[[items]]
title = "Pulp Fiction"

[[items]]
title = "Rear Window"

[[items]]
title = "Redline"

[[items]]
title = "Reservoir Dogs"

[[items]]
title = "Rosencrantz and Guildenstern Are Dead"

[[items]]
title = "SkyCrawlers"

[[items]]
title = "Smetto Quando Voglio"

[[items]]
title = "Spider-Man: Across the Spider-Verse"

[[items]]
title = "Summer Wars"

[[items]]
title = "Super Me"

[[items]]
title = "Suspiria (1977)"

[[items]]
title = "The Banshees of Inisherin"

[[items]]
title = "The Disaster Artist"

[[items]]
title = "The Fountain"

[[items]]
title = "The Gods Must Be Crazy"

[[items]]
title = "The Grand Budapest Hotel"

[[items]]
title = "The Great Mouse Detective"

[[items]]
title = "The Handmaiden"

[[items]]
title = "The Invitation"

[[items]]
title = "The Lobster"

[[items]]
title = "The Man From Earth"

[[items]]
title = "The Phoenician Scheme"

[[items]]
title = "The Rat Catcher"

[[items]]
title = "The Road to El Dorado"

[[items]]
title = "The Room"

[[items]]
title = "The Shape of Water"

[[items]]
title = "The Swan"

[[items]]
title = "The Vast of Night"

[[items]]
title = "The Verdict"

[[items]]
title = "This is Spinal Tap"

[[items]]
title = "Time Trap"

[[items]]
title = "Treasure Planet"

[[items]]
title = "Triangle of Sadness"

[[items]]
title = "Trollhunter"

[[items]]
title = "Uncut Gems"

[[items]]
title = "Weapons"

[[items]]
title = "Weird: The Al Yankovic Story"

[[items]]
title = "What About Bob?"

[[items]]
title = "Wish I Was Here"

[[items]]
title = "Your Name"
