# [[items]]
# id = "tt0068646"        # any globally-unique id (IMDB, MusicBrainz, ...)
# title = "The Godfather"
# year = 1972             # optional

[[items]]
title = "Austin Powers: Goldmember"

[[items]]
title = "Back to the Future"

[[items]]
title = "Battle Royale"

[[items]]
title = "Being John Malkovich"

[[items]]
title = "Big Daddy"

[[items]]
title = "Billy Madison"

[[items]]
title = "Chasing Amy"

[[items]]
title = "Children of Men"

[[items]]
title = "Coming to America"

[[items]]
title = "Constantine"

[[items]]
title = "Cool Runnings"

[[items]]
title = "Dark City"

[[items]]
title = "District 9"

[[items]]
title = "Dogma"

[[items]]
title = "Equilibrium"

[[items]]
title = "Eternal Sunshine of the Spotless Mind"

[[items]]
title = "Everything Everywhere All at Once"

[[items]]
title = "Farewell - ETAOIN SHRDLU"

[[items]]
title = "Garden State"

[[items]]
title = "Gattaca"

[[items]]
title = "Good Will Hunting"

[[items]]
title = "Grandma's Boy"

[[items]]
title = "Groundhog Day"

[[items]]
title = "Happy Gilmore"

[[items]]
title = "History of the World: Part One"

[[items]]
title = "Home Alone 2"

[[items]]
title = "Hot Fuzz"

[[items]]
title = "Howl's Moving Castle"

[[items]]
title = "Idiocracy"

[[items]]
title = "Inside Out"

[[items]]
title = "Jiro Dreams of Sushi"

[[items]]
title = "John Wick"

[[items]]
title = "Kill Bill"

[[items]]
title = "Leon: The Professional"

[[items]]
title = "Matilda"

[[items]]
title = "Memento"

[[items]]
title = "Monty Python and the Holy Grail"

[[items]]
title = "Mouse Hunt"

[[items]]
title = "My Cousin Vinny"

[[items]]
title = "My Neighbor Totoro"

[[items]]
title = "Office Space"

[[items]]
title = "Oldboy"

[[items]]
title = "Ponyo"

[[items]]
title = "Ratatouille"

[[items]]
title = "School of Rock"

[[items]]
title = "Se7en"

[[items]]
title = "Serenity"

[[items]]
title = "Shaun of the Dead"

[[items]]
title = "Six Days to Air: The Making of South Park"

[[items]]
title = "Snatch"

[[items]]
title = "Space Jam"

[[items]]
title = "Spaceballs"

[[items]]
title = "Spirited Away"

[[items]]
title = "Thank You for Smoking"

[[items]]
title = "The Breakfast Club"

[[items]]
title = "The Darjeeling Limited"

[[items]]
title = "The Fall"

[[items]]
title = "The Fifth Element"

[[items]]
title = "The Game"

[[items]]
title = "The Girl With the Dragon Tattoo"

[[items]]
title = "The Girl Who Played With Fire"

[[items]]
title = "The Girl Who Kicked the Hornets' Nest"

[[items]]
title = "The Incredibles"

[[items]]
title = "The Lord of the Rings: The Fellowship of the Ring"

[[items]]
title = "The Lord of the Rings: The Two Towers"

[[items]]
title = "The Lord of the Rings: Return of the King"

[[items]]
title = "The Matrix"

[[items]]
title = "The Ninth Gate"

[[items]]
title = "The Replacements"

[[items]]
title = "The Silence of the Lambs"

[[items]]
title = "The Thin Blue Line"

[[items]]
title = "The Trotsky"

[[items]]
title = "The Usual Suspects"

[[items]]
title = "Up"

[[items]]
title = "Wall-E"

[[items]]
title = "Wedding Crashers"

[[items]]
title = "Who Framed Roger Rabbit?"

[[items]]
title = "Willy Wonka & the Chocolate Factory"

[[items]]
title = "Wristcutters: A Love Story"
