[[items]]
id = "Austin Powers: Goldmember"
title = "Austin Powers: Goldmember"

[[items]]
id = "Back to the Future"
title = "Back to the Future"

[[items]]
id = "Battle Royale"
title = "Battle Royale"

[[items]]
id = "Being John Malkovich"
title = "Being John Malkovich"

[[items]]
id = "Big Daddy"
title = "Big Daddy"

[[items]]
id = "Billy Madison"
title = "Billy Madison"

[[items]]
id = "Chasing Amy"
title = "Chasing Amy"

[[items]]
id = "Children of Men"
title = "Children of Men"

[[items]]
id = "Coming to America"
title = "Coming to America"

[[items]]
id = "Constantine"
title = "Constantine"

[[items]]
id = "Cool Runnings"
title = "Cool Runnings"

[[items]]
id = "Dark City"
title = "Dark City"

[[items]]
id = "District 9"
title = "District 9"

[[items]]
id = "Dogma"
title = "Dogma"

[[items]]
id = "Equilibrium"
title = "Equilibrium"

[[items]]
id = "Eternal Sunshine of the Spotless Mind"
title = "Eternal Sunshine of the Spotless Mind"

[[items]]
id = "Everything Everywhere All at Once"
title = "Everything Everywhere All at Once"

[[items]]
id = "Farewell - ETAOIN SHRDLU"
title = "Farewell - ETAOIN SHRDLU"

[[items]]
id = "Garden State"
title = "Garden State"

[[items]]
id = "Gattaca"
title = "Gattaca"

[[items]]
id = "Good Will Hunting"
title = "Good Will Hunting"

[[items]]
id = "Grandma's Boy"
title = "Grandma's Boy"

[[items]]
id = "Groundhog Day"
title = "Groundhog Day"

[[items]]
id = "Happy Gilmore"
title = "Happy Gilmore"

[[items]]
id = "History of the World: Part One"
title = "History of the World: Part One"

[[items]]
id = "Home Alone 2"
title = "Home Alone 2"

[[items]]
id = "Hot Fuzz"
title = "Hot Fuzz"

[[items]]
id = "Howl's Moving Castle"
title = "Howl's Moving Castle"

[[items]]
id = "Idiocracy"
title = "Idiocracy"

[[items]]
id = "Inside Out"
title = "Inside Out"

[[items]]
id = "Jiro Dreams of Sushi"
title = "Jiro Dreams of Sushi"

[[items]]
id = "John Wick"
title = "John Wick"

[[items]]
id = "Kill Bill"
title = "Kill Bill"

[[items]]
id = "Leon: The Professional"
title = "Leon: The Professional"

[[items]]
id = "Matilda"
title = "Matilda"

[[items]]
id = "Memento"
title = "Memento"

[[items]]
id = "Monty Python and the Holy Grail"
title = "Monty Python and the Holy Grail"

[[items]]
id = "Mouse Hunt"
title = "Mouse Hunt"

[[items]]
id = "My Cousin Vinny"
title = "My Cousin Vinny"

[[items]]
id = "My Neighbor Totoro"
title = "My Neighbor Totoro"

[[items]]
id = "Office Space"
title = "Office Space"

[[items]]
id = "Oldboy"
title = "Oldboy"

[[items]]
id = "Ponyo"
title = "Ponyo"

[[items]]
id = "Ratatouille"
title = "Ratatouille"

[[items]]
id = "School of Rock"
title = "School of Rock"

[[items]]
id = "Se7en"
title = "Se7en"

[[items]]
id = "Serenity"
title = "Serenity"

[[items]]
id = "Shaun of the Dead"
title = "Shaun of the Dead"

[[items]]
id = "Six Days to Air: The Making of South Park"
title = "Six Days to Air: The Making of South Park"

[[items]]
id = "Snatch"
title = "Snatch"

[[items]]
id = "Space Jam"
title = "Space Jam"

[[items]]
id = "Spaceballs"
title = "Spaceballs"

[[items]]
id = "Spirited Away"
title = "Spirited Away"

[[items]]
id = "Thank You for Smoking"
title = "Thank You for Smoking"

[[items]]
id = "The Breakfast Club"
title = "The Breakfast Club"

[[items]]
id = "The Darjeeling Limited"
title = "The Darjeeling Limited"

[[items]]
id = "The Fall"
title = "The Fall"

[[items]]
id = "The Fifth Element"
title = "The Fifth Element"

[[items]]
id = "The Game"
title = "The Game"

[[items]]
id = "The Girl With the Dragon Tattoo"
title = "The Girl With the Dragon Tattoo"

[[items]]
id = "The Girl Who Played With Fire"
title = "The Girl Who Played With Fire"

[[items]]
id = "The Girl Who Kicked the Hornets' Nest"
title = "The Girl Who Kicked the Hornets' Nest"

[[items]]
id = "The Incredibles"
title = "The Incredibles"

[[items]]
id = "The Lord of the Rings: The Fellowship of the Ring"
title = "The Lord of the Rings: The Fellowship of the Ring"

[[items]]
id = "The Lord of the Rings: The Two Towers"
title = "The Lord of the Rings: The Two Towers"

[[items]]
id = "The Lord of the Rings: Return of the King"
title = "The Lord of the Rings: Return of the King"

[[items]]
id = "The Matrix"
title = "The Matrix"

[[items]]
id = "The Ninth Gate"
title = "The Ninth Gate"

[[items]]
id = "The Replacements"
title = "The Replacements"

[[items]]
id = "The Silence of the Lambs"
title = "The Silence of the Lambs"

[[items]]
id = "The Thin Blue Line"
title = "The Thin Blue Line"

[[items]]
id = "The Trotsky"
title = "The Trotsky"

[[items]]
id = "The Usual Suspects"
title = "The Usual Suspects"

[[items]]
id = "Up"
title = "Up"

[[items]]
id = "Wall-E"
title = "Wall-E"

[[items]]
id = "Wedding Crashers"
title = "Wedding Crashers"

[[items]]
id = "Who Framed Roger Rabbit?"
title = "Who Framed Roger Rabbit?"

[[items]]
id = "Willy Wonka & the Chocolate Factory"
title = "Willy Wonka & the Chocolate Factory"

[[items]]
id = "Wristcutters: A Love Story"
title = "Wristcutters: A Love Story"

[[items]]
id = "Michael"
title = "Michael"
